// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNJ0CtZeBSwlPpaAE2o3hy-6kPkg6eMlM',
    appId: '1:35841216629:web:85cc59c5882b901419e83c',
    messagingSenderId: '35841216629',
    projectId: 'tictactoe-dfc56',
    authDomain: 'tictactoe-dfc56.firebaseapp.com',
    storageBucket: 'tictactoe-dfc56.appspot.com',
    measurementId: 'G-167Z5BWM4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFuDe7WNN25KIUnh-0G_Vrw9EQzn0vD90',
    appId: '1:35841216629:android:4da0a490b520d49119e83c',
    messagingSenderId: '35841216629',
    projectId: 'tictactoe-dfc56',
    storageBucket: 'tictactoe-dfc56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbaPbDnN1Dz4jxuEPddQJhwZVWPMIxKs8',
    appId: '1:35841216629:ios:92ec458d576cec0919e83c',
    messagingSenderId: '35841216629',
    projectId: 'tictactoe-dfc56',
    storageBucket: 'tictactoe-dfc56.appspot.com',
    iosBundleId: 'com.roseik.tictactoe.tictactoe',
  );
}
